### ISSUE TITLE
Clean up for deployment part I

### ISSUE THREAD

**Issue by wllmwu** [TritonSE/TAP-Foster-Dog-Matching#102]
- [x] [Frontend] Admin side - no confirmation after initial interview (step 2) is passed, or step 4 dog is chosen, or step 5 after meet and greet confirmed - show a popup saying "Interview confirmed!" or similar first; when showing the page afterwards, check for existence of message in application object and disable the confirm button if present
- [x] [Frontend] Foster profile component - make it wider and fix the padding
- [x] [Frontend] Change default confirmation messages to have more obvious placeholders
- [x] [Frontend] Use standard status update component for meet and greet (step 5) on admin side
- [x] [Frontend] Implement internal foster notes
- [x] [Frontend] Step 4 foster profile and internal foster notes are hardcoded - use existing foster profile component and fill internal notes from application object

**Comment by petabite** [comment]
> [Frontend] Admin side - no confirmation after initial interview (step 2) is passed, or step 4 dog is chosen, or step 5 after meet and greet confirmed - show a popup saying "Interview confirmed!" or similar first; when showing the page afterwards, check for existence of message in application object and disable the confirm button if present

even better: I figured out we can just advance to the next step when "confirm" is clicked.
