### ISSUE TITLE
Connect Application Page Progress to Backend

### ISSUE THREAD

**Issue by dnanjunda** [TritonSE/TAP-Foster-Dog-Matching#68]
The progress bar on the application page should reflect whatever stage the application is currently in. Also, from both an admin's POV and a user's POV, whenever an action is taken by one of the them (schedule an interview, pass a stage, etc.), the application page needs to be updated to reflect that.

**Comment by wllmwu** [comment]
Currently can't click on different stages in the progress bar

Edit 2023-03-06: done

**Comment by wllmwu** [comment]
Includes both foster and admin sides

**Comment by wllmwu** [comment]
2023-03-06:
- Need ambassador to be assigned before any interviews can be scheduled
- Stage 4 on admin side displays wrong component
- Move the "click on me" card from stage 4 to stage 5 on foster side and make the stage advancement route protected (admins only)
