### ISSUE TITLE
Setup Image Hosting

### ISSUE THREAD

**Issue by dnanjunda** [TritonSE/TAP-Foster-Dog-Matching#70]
Will be used for profile photos, dog images, and other images used throughout the website

**Comment by wllmwu** [comment]
@petabite investigate using Firebase to host images, begin backend implementation

**Comment by wllmwu** [comment]
Todo: Change default profile and dog pictures

**Comment by petabite** [comment]
new firebase feature ftw: https://extensions.dev/extensions/firebase/storage-resize-images 

EDIT: This also needs a credit card to use

**Comment by petabite** [comment]
# Frontend Tasks
- [x] Change default profile and dog pictures
- [x] Implement dog picture uploading in Create Dog Form
- [x] Implement admin profile picture uploading in Edit Profile Modal
- [x] Fix all image-related TODOs in the codebase 
- [x] Find all imports of the default hardcoded images and remove them
- [x] Delete all hardcoded images from `images` folder
